# Generated by Django 2.2 on 2021-02-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210209_2041'),
        ('users', '0003_auto_20210211_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shoplist',
            field=models.ManyToManyField(related_name='added_to_shoplist_by', to='recipes.Recipe'),
        ),
    ]
