version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: sudomoinpavel/foodgram-project:latest
    restart: always
    command: >
      bash -c "python manage.py migrate --noinput
      && python manage.py collectstatic --noinput
      && python manage.py loaddata fixtures_ingredients.json
      && gunicorn foodgram.wsgi:application --bind 0.0.0.0:8020"
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
      - 8020
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.5
    restart: unless-stopped
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      -  web
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      -  web
